language: go

# USE THIS alongside makefile tag detection: $TRAVIS_TAG

go: 
 - 1.10.x      # current version
 - 1.11.x      # current version

# Speed up git clones
git:
  depth: 1


# Anything in before_script that returns a nonzero exit code will
# flunk the build and immediately stop. It's sorta like having
# set -e enabled in bash. 
before_script:
  #- sudo apt-get -qq update && sudo apt-get install -y ldap-utils oathtool  # need this for integration tests
  #- sudo apt-get -qq update && sudo apt-get install -y go-bindata           # need this for makefile
  # - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)             # All the .go files, excluding vendor/
  #- go get github.com/golang/lint/golint                                   # Linter
  #- go get honnef.co/go/tools/cmd/megacheck                                # Badass static analyzer/linter
  # - go get github.com/fzipp/gocyclo                                       # Not sure what this is

# Run bindata for assets
#  - make bindata


script:
  - env                                       # Dump the env to make debugging easier
  - diff -u <(echo -n) <(gofmt -d ./)         # Fail if a .go file hasn't been formatted with 'go fmt'
  - go vet ./...        "                     # go vet is the official Go static analyzer
  - go test -v -race ./...                    # Run all the tests with the race detector enabled
  # TODO: Get these working for additional checks
  # - megacheck ./...                          # "go vet on steroids" + linter
  # - gocyclo -over 19 $GO_FILES               # forbid code with huge functions
  # - golint -set_exit_status $(go list ./...) # one last linter


  # Unit tests for codecov.io
  - go test -race -coverprofile=coverage.txt -covermode=atomic

  # Full compile test
  - go build

  # Output hashes to the build log
  - sha256sum deadcron

# after_success:
#  - bash <(curl -s https://codecov.io/bash)

# Leaving here for future use
#deploy:
#  provider: releases
#  api_key:
#    secure: [fillinlater]
#  file_glob: true 
#  file: bin/*
#  draft: true
#  name: "DRAFT RELEASE: $TRAVIS_TAG"
#  body: "Draft release, committed with message: $TRAVIS_COMMIT_MESSAGE"
#  body: "# Commit Details<br />$TRAVIS_COMMIT_MESSAGE<br /><br /># Note About Non-Linux 64bit Files<br /> While I expect the code is system-independent, there is not a good (and free) CI system which can be easily used to continuously test releases on ARM, BSD, Linux-32bit, and Windows.<br /><br />As such, the primary release platform is Linux 64 bit. The extent of testing on these packages consists solely of cross-compiling for these architectures from a linux 64 bit system.<br /><br />We will accept PRs which fix bugs on these platforms, but be aware these binaries will not be tested regularly, and instead are provided for the convenience of those who feel comfortable using them with this knowledge."

#  skip_cleanup: true
#  on:
#    branch: master
#    tags: true
#    condition: $TRAVIS_GO_VERSION = "1.10.1"
